version: '3.4'

services:
  test:
    image: golang:1.10-alpine3.8
    volumes:
      - ./:/go/src/github.com/imega/sensible-breakpoints
    working_dir: "/go/src/github.com/imega/sensible-breakpoints"
    command: >
      /bin/sh -c "
        go test -v github.com/imega/sensible-breakpoints
      "
